[package]
name = "rust-wasm-ffi"
version = "0.1.0"
edition = "2021"
rust-version = "1.57"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.90"
libc = "0.2"

[build-dependencies]
cc = "1.0"

[dev-dependencies]
wasm-bindgen-test = "0.3.40"
